### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by OKNoah** [dabit3/react-native-navigator-experimental-redux#3]
This, after clone, npm install and `react-native run-ios`.

```
** BUILD FAILED **


The following build commands failed:
  CompileC /Users/my-user/Documents/dev/react-native-navigator-experimental-redux/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/RNExperimentalRedux.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/my-user/Documents/dev/react-native-navigator-experimental-redux/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RNExperimentalRedux.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:469:13)
    at Object.execFileSync (child_process.js:489:13)
    at _runIOS (/Users/my-user/Documents/dev/react-native-navigator-experimental-redux/node_modules/react-native/local-cli/runIOS/runIOS.js:91:34)
    at /Users/my-user/Documents/dev/react-native-navigator-experimental-redux/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5
    at tryCallTwo (/Users/my-user/Documents/dev/react-native-navigator-experimental-redux/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/my-user/Documents/dev/react-native-navigator-experimental-redux/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/my-user/Documents/dev/react-native-navigator-experimental-redux/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/my-user/Documents/dev/react-native-navigator-experimental-redux/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/my-user/Documents/dev/react-native-navigator-experimental-redux/node_modules/react-native/local-cli/cliEntry.js:91:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)
```

**Comment by jamesjenner** [comment]
+1 getting the same issue. Did you resolve it @OKNoah ?
